name: Release Steps
on:
  push:
    tags:
      - '*'

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          # Retrieves all commit history for path filter checking
          fetch-depth: 0
      - name: setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: install Poetry
        uses: snok/install-poetry@v1.3.3
      - name: configure pypi credentials
        run: poetry config pypi-token.pypi "${{ secrets.PYPI_API_KEY }}"
      - name: Publish package
        run: poetry publish --build
      - name: metadata filter
        uses: tj-actions/changed-files@v33
        id: metadata-filter
        with:
          files: |
            openstates/metadata
            openstates/data
            openstates/cli/initdb.py
            .github/workflows/release.yml
          files_ignore: |
            openstates/metadata/tests
            openstates/data/tests
      - name: install dependencies
        if: "steps.metadata-filter.outputs.any_changed == 'true'"
        run: poetry install
      - name: update metadata
        if: "steps.metadata-filter.outputs.any_changed == 'true'"
        env:
          DATABASE_URL: ${{ secrets.OPENSTATES_DATABASE_URL }}
        run: poetry run os-initdb
